# Generated by Django 4.2.5 on 2023-09-22 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_lesson_delete_lession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='product',
            new_name='products',
        ),
    ]
