# Generated by Django 4.2.5 on 2023-09-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_product_lesson_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='view_status',
            field=models.CharField(choices=[('Viewed', 'Viewed'), ('Not viewed', 'Not viewed')], default=('Viewed', 'Viewed'), max_length=100),
        ),
    ]
