# Generated by Django 4.2.5 on 2023-09-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_lesson_view_status_lessonprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogress',
            name='view_status',
            field=models.CharField(choices=[('not_viewed', 'Not viewed'), ('viewed', 'Viewed')], default=('not_viewed', 'Not viewed'), max_length=100),
        ),
    ]
